import { Instance, Platform } from "./types";

type CloudPlatForm = Platform.AWS | Platform.AZURE | Platform.GCP;

type PlatformInstanceMap = {
  [platform in CloudPlatForm]: Instance[];
};

export const platformInstanceMap: PlatformInstanceMap = {
  [Platform.AWS]: [
    {
      name: "c3.2xlarge",
      memory: 15,
      cpuUnits: 8,
      instanceStorage: 160,
    },
    {
      name: "c3.4xlarge",
      memory: 30,
      cpuUnits: 16,
      instanceStorage: 320,
    },
    {
      name: "c3.8xlarge",
      memory: 60,
      cpuUnits: 32,
      instanceStorage: 640,
    },
    {
      name: "c3.large",
      memory: 3.75,
      cpuUnits: 2,
      instanceStorage: 32,
    },
    {
      name: "c3.xlarge",
      memory: 7.5,
      cpuUnits: 4,
      instanceStorage: 80,
    },
    {
      name: "c5ad.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "c5ad.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "c5ad.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 3800,
    },
    {
      name: "c5ad.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "c5ad.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "c5ad.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "c5ad.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "c5ad.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "c5d.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "c5d.18xlarge",
      memory: 144,
      cpuUnits: 72,
      instanceStorage: 1800,
    },
    {
      name: "c5d.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "c5d.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 200,
    },
    {
      name: "c5d.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 400,
    },
    {
      name: "c5d.9xlarge",
      memory: 72,
      cpuUnits: 36,
      instanceStorage: 900,
    },
    {
      name: "c5d.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 50,
    },
    {
      name: "c5d.metal",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "c5d.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 100,
    },
    {
      name: "c6gd.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "c6gd.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "c6gd.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 474,
    },
    {
      name: "c6gd.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "c6gd.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "c6gd.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "c6gd.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "c6gd.metal",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "c6gd.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "cr1.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 240,
    },
    {
      name: "f1.16xlarge",
      memory: 976,
      cpuUnits: 64,
      instanceStorage: 3760,
    },
    {
      name: "f1.2xlarge",
      memory: 122,
      cpuUnits: 8,
      instanceStorage: 470,
    },
    {
      name: "f1.4xlarge",
      memory: 244,
      cpuUnits: 16,
      instanceStorage: 940,
    },
    {
      name: "g2.2xlarge",
      memory: 15,
      cpuUnits: 8,
      instanceStorage: 60,
    },
    {
      name: "g2.8xlarge",
      memory: 60,
      cpuUnits: 32,
      instanceStorage: 240,
    },
    {
      name: "g4ad.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "g4ad.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "g4ad.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "g4dn.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 900,
    },
    {
      name: "g4dn.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 900,
    },
    {
      name: "g4dn.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 225,
    },
    {
      name: "g4dn.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 225,
    },
    {
      name: "g4dn.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 900,
    },
    {
      name: "g4dn.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 1800,
    },
    {
      name: "g4dn.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 125,
    },
    {
      name: "i2.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 1600,
    },
    {
      name: "i2.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 3200,
    },
    {
      name: "i2.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 6400,
    },
    {
      name: "i2.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 800,
    },
    {
      name: "i3.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 15200,
    },
    {
      name: "i3.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 1900,
    },
    {
      name: "i3.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 3800,
    },
    {
      name: "i3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 7600,
    },
    {
      name: "i3.large",
      memory: 15.25,
      cpuUnits: 2,
      instanceStorage: 475,
    },
    {
      name: "i3.metal",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 15200,
    },
    {
      name: "i3.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 950,
    },
    {
      name: "i3en.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 30000,
    },
    {
      name: "i3en.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 60000,
    },
    {
      name: "i3en.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 5000,
    },
    {
      name: "i3en.3xlarge",
      memory: 96,
      cpuUnits: 12,
      instanceStorage: 7500,
    },
    {
      name: "i3en.6xlarge",
      memory: 192,
      cpuUnits: 24,
      instanceStorage: 15000,
    },
    {
      name: "i3en.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 1250,
    },
    {
      name: "i3en.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 60000,
    },
    {
      name: "i3en.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 2500,
    },
    {
      name: "m3.2xlarge",
      memory: 30,
      cpuUnits: 8,
      instanceStorage: 160,
    },
    {
      name: "m3.large",
      memory: 7.5,
      cpuUnits: 2,
      instanceStorage: 32,
    },
    {
      name: "m3.medium",
      memory: 3.75,
      cpuUnits: 1,
      instanceStorage: 4,
    },
    {
      name: "m3.xlarge",
      memory: 15,
      cpuUnits: 4,
      instanceStorage: 80,
    },
    {
      name: "m5ad.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "m5ad.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "m5ad.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5ad.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "m5ad.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "m5ad.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "m5ad.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "m5ad.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "m5d.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "m5d.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "m5d.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5d.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "m5d.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "m5d.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "m5d.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "m5d.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5d.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "m5dn.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "m5dn.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "m5dn.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5dn.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "m5dn.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "m5dn.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "m5dn.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "m5dn.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5dn.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "m6gd.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "m6gd.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "m6gd.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 474,
    },
    {
      name: "m6gd.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "m6gd.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "m6gd.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "m6gd.medium",
      memory: 4,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "m6gd.metal",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "m6gd.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "p3dn.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 1800,
    },
    {
      name: "p4d.24xlarge",
      memory: 1152,
      cpuUnits: 96,
      instanceStorage: 8000,
    },
    {
      name: "r3.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 160,
    },
    {
      name: "r3.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 320,
    },
    {
      name: "r3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 640,
    },
    {
      name: "r3.large",
      memory: 15.25,
      cpuUnits: 2,
      instanceStorage: 32,
    },
    {
      name: "r3.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 80,
    },
    {
      name: "r5ad.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "r5ad.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "r5ad.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5ad.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "r5ad.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "r5ad.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "r5ad.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "r5ad.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "r5d.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "r5d.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "r5d.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5d.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "r5d.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "r5d.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "r5d.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "r5d.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5d.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "r5dn.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "r5dn.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "r5dn.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5dn.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "r5dn.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "r5dn.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "r5dn.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "r5dn.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5dn.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "r6gd.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "r6gd.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "r6gd.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 474,
    },
    {
      name: "r6gd.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "r6gd.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "r6gd.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "r6gd.medium",
      memory: 8,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "r6gd.metal",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "r6gd.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "x1.16xlarge",
      memory: 976,
      cpuUnits: 64,
      instanceStorage: 1920,
    },
    {
      name: "x1.32xlarge",
      memory: 1952,
      cpuUnits: 128,
      instanceStorage: 3840,
    },
    {
      name: "x1e.16xlarge",
      memory: 1952,
      cpuUnits: 64,
      instanceStorage: 1920,
    },
    {
      name: "x1e.2xlarge",
      memory: 244,
      cpuUnits: 8,
      instanceStorage: 240,
    },
    {
      name: "x1e.32xlarge",
      memory: 3904,
      cpuUnits: 128,
      instanceStorage: 3840,
    },
    {
      name: "x1e.4xlarge",
      memory: 488,
      cpuUnits: 16,
      instanceStorage: 480,
    },
    {
      name: "x1e.8xlarge",
      memory: 976,
      cpuUnits: 32,
      instanceStorage: 960,
    },
    {
      name: "x1e.xlarge",
      memory: 122,
      cpuUnits: 4,
      instanceStorage: 120,
    },
    {
      name: "x2gd.12xlarge",
      memory: 768,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "x2gd.16xlarge",
      memory: 1024,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "x2gd.2xlarge",
      memory: 128,
      cpuUnits: 8,
      instanceStorage: 475,
    },
    {
      name: "x2gd.4xlarge",
      memory: 256,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "x2gd.8xlarge",
      memory: 512,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "x2gd.large",
      memory: 32,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "x2gd.medium",
      memory: 16,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "x2gd.metal",
      memory: 1024,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "x2gd.xlarge",
      memory: 64,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "z1d.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "z1d.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "z1d.3xlarge",
      memory: 96,
      cpuUnits: 12,
      instanceStorage: 450,
    },
    {
      name: "z1d.6xlarge",
      memory: 192,
      cpuUnits: 24,
      instanceStorage: 900,
    },
    {
      name: "z1d.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "z1d.metal",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "z1d.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "a1.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "a1.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "a1.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "a1.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "a1.metal",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "a1.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c1.medium",
      memory: 1.7,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c1.xlarge",
      memory: 7,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c4.2xlarge",
      memory: 15,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c4.4xlarge",
      memory: 30,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c4.8xlarge",
      memory: 60,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "c4.large",
      memory: 3.75,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c4.xlarge",
      memory: 7.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c5.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c5.18xlarge",
      memory: 144,
      cpuUnits: 72,
      instanceStorage: 0,
    },
    {
      name: "c5.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "c5.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c5.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c5.9xlarge",
      memory: 72,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "c5.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c5.metal",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "c5.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c5a.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c5a.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c5a.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "c5a.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c5a.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c5a.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "c5a.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c5a.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c5n.18xlarge",
      memory: 192,
      cpuUnits: 72,
      instanceStorage: 0,
    },
    {
      name: "c5n.2xlarge",
      memory: 21,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c5n.4xlarge",
      memory: 42,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c5n.9xlarge",
      memory: 96,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "c5n.large",
      memory: 5.25,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c5n.metal",
      memory: 192,
      cpuUnits: 72,
      instanceStorage: 0,
    },
    {
      name: "c5n.xlarge",
      memory: 10.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c6g.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c6g.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6g.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c6g.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c6g.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "c6g.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c6g.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "c6g.metal",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6g.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c6gn.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c6gn.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6gn.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c6gn.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c6gn.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "c6gn.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c6gn.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "c6gn.metal",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6gn.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "cc2.8xlarge",
      memory: 60.5,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "d2.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "d2.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "d2.8xlarge",
      memory: 244,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "d2.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "d3.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "d3.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "d3.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "d3.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "d3en.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "d3en.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "d3en.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "d3en.6xlarge",
      memory: 96,
      cpuUnits: 24,
      instanceStorage: 0,
    },
    {
      name: "d3en.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "d3en.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "g3.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "g3.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "g3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "g3s.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "h1.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "h1.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "h1.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "h1.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "hs1.8xlarge",
      memory: 117,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "i2.large",
      memory: 15,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "inf1.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "inf1.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "inf1.6xlarge",
      memory: 48,
      cpuUnits: 24,
      instanceStorage: 0,
    },
    {
      name: "inf1.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m1.large",
      memory: 7.5,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m1.medium",
      memory: 3.75,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "m1.small",
      memory: 1.7,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "m1.xlarge",
      memory: 15,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m2.2xlarge",
      memory: 34.2,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m2.4xlarge",
      memory: 68.4,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m2.xlarge",
      memory: 17.1,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m4.10xlarge",
      memory: 160,
      cpuUnits: 40,
      instanceStorage: 0,
    },
    {
      name: "m4.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m4.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m4.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m4.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m4.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m5.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m5.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m5.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m5.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
      default: true,
    },
    {
      name: "m5.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
      controlPlane: true,
    },
    {
      name: "m5a.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5a.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m5a.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5a.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5a.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m5a.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m5a.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m5a.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m5n.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5n.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m5n.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5n.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5n.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m5n.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m5n.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m5n.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5n.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m5zn.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5zn.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5zn.3xlarge",
      memory: 48,
      cpuUnits: 12,
      instanceStorage: 0,
    },
    {
      name: "m5zn.6xlarge",
      memory: 96,
      cpuUnits: 24,
      instanceStorage: 0,
    },
    {
      name: "m5zn.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m5zn.metal",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5zn.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m6g.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m6g.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m6g.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m6g.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m6g.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m6g.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m6g.medium",
      memory: 4,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "m6g.metal",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m6g.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "mac1.metal",
      memory: 32,
      cpuUnits: 12,
      instanceStorage: 0,
    },
    {
      name: "p2.16xlarge",
      memory: 732,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "p2.8xlarge",
      memory: 488,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "p2.xlarge",
      memory: 61,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "p3.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "p3.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "p3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r4.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r4.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r4.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r4.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r4.large",
      memory: 15.25,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r4.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5a.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5a.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5a.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5a.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5a.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5a.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5a.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5a.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5b.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5b.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5b.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5b.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5b.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5b.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5b.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5b.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5b.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5n.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5n.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5n.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5n.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5n.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5n.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5n.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5n.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5n.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r6g.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r6g.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r6g.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r6g.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r6g.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r6g.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r6g.medium",
      memory: 8,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "r6g.metal",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r6g.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "u-12tb1.metal",
      memory: 12288,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-18tb1.metal",
      memory: 18432,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-24tb1.metal",
      memory: 24576,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-6tb1.metal",
      memory: 6144,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-9tb1.metal",
      memory: 9216,
      cpuUnits: 448,
      instanceStorage: 0,
    },
  ],
  [Platform.AZURE]: [
    {
      name: "Basic_A3",
      cpuUnits: 4,
      memory: 7,
      instanceStorage: 0,
    },
    {
      name: "Basic_A4",
      cpuUnits: 8,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_A1_v2",
      cpuUnits: 1,
      memory: 2,
      instanceStorage: 10,
    },
    {
      name: "Standard_A2_v2",
      cpuUnits: 2,
      memory: 4,
      instanceStorage: 20,
    },
    {
      name: "Standard_A2m_v2",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 20,
    },
    {
      name: "Standard_A3",
      cpuUnits: 4,
      memory: 7,
      instanceStorage: 0,
    },
    {
      name: "Standard_A4",
      cpuUnits: 8,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_A4_v2",
      cpuUnits: 4,
      memory: 8,
      instanceStorage: 40,
    },
    {
      name: "Standard_A4m_v2",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 40,
    },
    {
      name: "Standard_A5",
      cpuUnits: 2,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_A6",
      cpuUnits: 4,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_A7",
      cpuUnits: 8,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_A8_v2",
      cpuUnits: 8,
      memory: 16,
      instanceStorage: 80,
    },
    {
      name: "Standard_A8m_v2",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 80,
    },
    {
      name: "Standard_B1s",
      cpuUnits: 1,
      memory: 1,
      instanceStorage: 4,
    },
    {
      name: "Standard_B1ms",
      cpuUnits: 1,
      memory: 2,
      instanceStorage: 4,
    },
    {
      name: "Standard_B2s",
      cpuUnits: 2,
      memory: 4,
      instanceStorage: 8,
    },
    {
      name: "Standard_B2ms",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 16,
    },
    {
      name: "Standard_B4ms",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 32,
    },
    {
      name: "Standard_B8ms",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 64,
    },
    {
      name: "Standard_B12ms",
      cpuUnits: 12,
      memory: 48,
      instanceStorage: 96,
    },
    {
      name: "Standard_B16ms",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 128,
    },
    {
      name: "Standard_B20ms",
      cpuUnits: 20,
      memory: 80,
      instanceStorage: 160,
    },
    {
      name: "Standard_D11",
      cpuUnits: 2,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_D11_v2",
      cpuUnits: 2,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_D12",
      cpuUnits: 4,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_D12_v2",
      cpuUnits: 4,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_D13",
      cpuUnits: 8,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_D13_v2",
      cpuUnits: 8,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_D14",
      cpuUnits: 16,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_D14_v2",
      cpuUnits: 16,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_D15_v2",
      cpuUnits: 20,
      memory: 140,
      instanceStorage: 0,
    },
    {
      name: "Standard_D16_v3",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 400,
    },
    {
      name: "Standard_D16_v4",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_D16a_v4",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 400,
    },
    {
      name: "Standard_D16as_v4",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 128,
    },
    {
      name: "Standard_D16d_v4",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 600,
    },
    {
      name: "Standard_D16ds_v4",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 600,
    },
    {
      name: "Standard_D16s_v3",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 128,
    },
    {
      name: "Standard_D16s_v4",
      cpuUnits: 16,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_D2",
      cpuUnits: 2,
      memory: 7,
      instanceStorage: 0,
    },
    {
      name: "Standard_D2_v2",
      cpuUnits: 2,
      memory: 7,
      instanceStorage: 100,
    },
    {
      name: "Standard_D2_v3",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 50,
      default: true,
    },
    {
      name: "Standard_D2_v4",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 0,
    },
    {
      name: "Standard_D2a_v4",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 50,
    },
    {
      name: "Standard_D2as_v4",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 16,
    },
    {
      name: "Standard_D2d_v4",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 75,
    },
    {
      name: "Standard_D2ds_v4",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 75,
    },
    {
      name: "Standard_D2s_v3",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 16,
    },
    {
      name: "Standard_D2s_v4",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 0,
    },
    {
      name: "Standard_D3",
      cpuUnits: 4,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_D3_v2",
      cpuUnits: 4,
      memory: 14,
      instanceStorage: 200,
    },
    {
      name: "Standard_D32_v3",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 800,
    },
    {
      name: "Standard_D32_v4",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_D32a_v4",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 800,
    },
    {
      name: "Standard_D32as_v4",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 256,
    },
    {
      name: "Standard_D32d_v4",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 1200,
    },
    {
      name: "Standard_D32ds_v4",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 1200,
    },
    {
      name: "Standard_D32s_v3",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 256,
    },
    {
      name: "Standard_D32s_v4",
      cpuUnits: 32,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_D4",
      cpuUnits: 8,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_D4_v2",
      cpuUnits: 8,
      memory: 28,
      instanceStorage: 400,
    },
    {
      name: "Standard_D4_v3",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 8,
    },
    {
      name: "Standard_D4_v4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_D4a_v4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 100,
    },
    {
      name: "Standard_D4as_v4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 32,
    },
    {
      name: "Standard_D4d_v4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 150,
    },
    {
      name: "Standard_D4ds_v4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 150,
    },
    {
      name: "Standard_D4s_v3",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 32,
    },
    {
      name: "Standard_D4s_v4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_D48_v3",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 1200,
    },
    {
      name: "Standard_D48_v4",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 0,
    },
    {
      name: "Standard_D48a_v4",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 0,
    },
    {
      name: "Standard_D48as_v4",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 384,
    },
    {
      name: "Standard_D48d_v4",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 1800,
    },
    {
      name: "Standard_D48ds_v4",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 1800,
    },
    {
      name: "Standard_D48s_v3",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 384,
    },
    {
      name: "Standard_D48s_v4",
      cpuUnits: 48,
      memory: 192,
      instanceStorage: 0,
    },
    {
      name: "Standard_D5_v2",
      cpuUnits: 16,
      memory: 56,
      instanceStorage: 800,
    },
    {
      name: "Standard_D64_v3",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 1600,
    },
    {
      name: "Standard_D64_v4",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_D64a_v4",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 1600,
    },
    {
      name: "Standard_D64as_v4",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 512,
    },
    {
      name: "Standard_D64d_v4",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 2400,
    },
    {
      name: "Standard_D64ds_v4",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 2400,
    },
    {
      name: "Standard_D64s_v3",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 512,
    },
    {
      name: "Standard_D64s_v4",
      cpuUnits: 64,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_D8_v3",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 200,
    },
    {
      name: "Standard_D8_v4",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_D8a_v4",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 200,
    },
    {
      name: "Standard_D8as_v4",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 64,
    },
    {
      name: "Standard_D8d_v4",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 300,
    },
    {
      name: "Standard_D8ds_v4",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 300,
    },
    {
      name: "Standard_D8s_v3",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 64,
      controlPlane: true,
    },
    {
      name: "Standard_D8s_v4",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_D96a_v4",
      cpuUnits: 96,
      memory: 384,
      instanceStorage: 2400,
    },
    {
      name: "Standard_D96as_v4",
      cpuUnits: 96,
      memory: 384,
      instanceStorage: 768,
    },
    {
      name: "Standard_DC1s_v2",
      cpuUnits: 1,
      memory: 4,
      instanceStorage: 50,
    },
    {
      name: "Standard_DC2s_v2",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 100,
    },
    {
      name: "Standard_DC4s_v2",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 200,
    },
    {
      name: "Standard_DC8_v2",
      cpuUnits: 8,
      memory: 32,
      instanceStorage: 400,
    },
    {
      name: "Standard_DS11",
      cpuUnits: 2,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS11-1_v2",
      cpuUnits: 1,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS11_v2",
      cpuUnits: 2,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS12",
      cpuUnits: 4,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS12-1_v2",
      cpuUnits: 1,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS12-2_v2",
      cpuUnits: 2,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS12_v2",
      cpuUnits: 4,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS13",
      cpuUnits: 8,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS13-2_v2",
      cpuUnits: 2,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS13-4_v2",
      cpuUnits: 4,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS13_v2",
      cpuUnits: 8,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS14",
      cpuUnits: 8,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS14-4_v2",
      cpuUnits: 4,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS14-8_v2",
      cpuUnits: 8,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS14_v2",
      cpuUnits: 16,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS15_v2",
      cpuUnits: 20,
      memory: 140,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS2",
      cpuUnits: 2,
      memory: 7,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS2_v2",
      cpuUnits: 2,
      memory: 7,
      instanceStorage: 7,
    },
    {
      name: "Standard_DS3",
      cpuUnits: 4,
      memory: 14,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS3_v2",
      cpuUnits: 4,
      memory: 14,
      instanceStorage: 14,
    },
    {
      name: "Standard_DS4",
      cpuUnits: 8,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_DS4_v2",
      cpuUnits: 8,
      memory: 28,
      instanceStorage: 56,
    },
    {
      name: "Standard_DS5_v2",
      cpuUnits: 16,
      memory: 56,
      instanceStorage: 112,
    },
    {
      name: "Standard_E16-4as_v4",
      cpuUnits: 4,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16-4ds_v4",
      cpuUnits: 4,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16-4s_v3",
      cpuUnits: 4,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16-4s_v4",
      cpuUnits: 4,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16-8as_v4",
      cpuUnits: 8,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16-8ds_v4",
      cpuUnits: 8,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16-8s_v3",
      cpuUnits: 8,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16-8s_v4",
      cpuUnits: 8,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16_v3",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16_v4",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16a_v4",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16as_v4",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16d_v4",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16ds_v4",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16s_v3",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E16s_v4",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2_v3",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2_v4",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2a_v4",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2as_v4",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2d_v4",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2ds_v4",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2s_v3",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E2s_v4",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20_v3",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20_v4",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20a_v4",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20as_v4",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20d_v4",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20ds_v4",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20s_v3",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E20s_v4",
      cpuUnits: 20,
      memory: 160,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-16as_v4",
      cpuUnits: 16,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-16ds_v4",
      cpuUnits: 16,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-16s_v3",
      cpuUnits: 16,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-16s_v4",
      cpuUnits: 16,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-8as_v4",
      cpuUnits: 8,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-8ds_v4",
      cpuUnits: 8,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-8s_v3",
      cpuUnits: 8,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32-8s_v4",
      cpuUnits: 8,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32_v3",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32_v4",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32a_v4",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32as_v4",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32d_v4",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32ds_v4",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32s_v3",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E32s_v4",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4-2as_v4",
      cpuUnits: 2,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4-2ds_v4",
      cpuUnits: 2,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4-2s_v3",
      cpuUnits: 2,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4-2s_v4",
      cpuUnits: 2,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4_v3",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4_v4",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4a_v4",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4as_v4",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4d_v4",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4ds_v4",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4s_v3",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E4s_v4",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48_v3",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48_v4",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48a_v4",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48as_v4",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48d_v4",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48ds_v4",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48s_v3",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E48s_v4",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-16as_v4",
      cpuUnits: 16,
      memory: 512,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-16ds_v4",
      cpuUnits: 16,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-16s_v3",
      cpuUnits: 16,
      memory: 432,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-16s_v4",
      cpuUnits: 16,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-32as_v4",
      cpuUnits: 32,
      memory: 512,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-32ds_v4",
      cpuUnits: 32,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-32s_v3",
      cpuUnits: 32,
      memory: 432,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64-32s_v4",
      cpuUnits: 32,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64_v3",
      cpuUnits: 64,
      memory: 432,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64_v4",
      cpuUnits: 64,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64a_v4",
      cpuUnits: 64,
      memory: 512,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64as_v4",
      cpuUnits: 64,
      memory: 512,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64d_v4",
      cpuUnits: 64,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64ds_v4",
      cpuUnits: 64,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64i_v3",
      cpuUnits: 64,
      memory: 432,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64is_v3",
      cpuUnits: 64,
      memory: 432,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64s_v3",
      cpuUnits: 64,
      memory: 432,
      instanceStorage: 0,
    },
    {
      name: "Standard_E64s_v4",
      cpuUnits: 64,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-2as_v4",
      cpuUnits: 2,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-2ds_v4",
      cpuUnits: 2,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-2s_v3",
      cpuUnits: 2,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-2s_v4",
      cpuUnits: 2,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-4as_v4",
      cpuUnits: 4,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-4ds_v4",
      cpuUnits: 4,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-4s_v3",
      cpuUnits: 4,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8-4s_v4",
      cpuUnits: 4,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8_v3",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8_v4",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8a_v4",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8as_v4",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8d_v4",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8ds_v4",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8s_v3",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E8s_v4",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_E80ids_v4",
      cpuUnits: 80,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E80is_v4",
      cpuUnits: 80,
      memory: 504,
      instanceStorage: 0,
    },
    {
      name: "Standard_E96-24as_v4",
      cpuUnits: 24,
      memory: 672,
      instanceStorage: 0,
    },
    {
      name: "Standard_E96-48as_v4",
      cpuUnits: 48,
      memory: 672,
      instanceStorage: 0,
    },
    {
      name: "Standard_E96a_v4",
      cpuUnits: 96,
      memory: 672,
      instanceStorage: 0,
    },
    {
      name: "Standard_E96as_v4",
      cpuUnits: 96,
      memory: 672,
      instanceStorage: 0,
    },
    {
      name: "Standard_F1s",
      cpuUnits: 1,
      memory: 2,
      instanceStorage: 0,
    },
    {
      name: "Standard_F1",
      cpuUnits: 1,
      memory: 2,
      instanceStorage: 0,
    },
    {
      name: "Standard_F16",
      cpuUnits: 16,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_F16s",
      cpuUnits: 16,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_F16s_v2",
      cpuUnits: 16,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_F2s",
      cpuUnits: 2,
      memory: 4,
      instanceStorage: 0,
    },
    {
      name: "Standard_F2",
      cpuUnits: 2,
      memory: 4,
      instanceStorage: 0,
    },
    {
      name: "Standard_F2s_v2",
      cpuUnits: 2,
      memory: 4,
      instanceStorage: 0,
    },
    {
      name: "Standard_F32s_v2",
      cpuUnits: 32,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_F4s",
      cpuUnits: 4,
      memory: 8,
      instanceStorage: 0,
    },
    {
      name: "Standard_F4",
      cpuUnits: 4,
      memory: 8,
      instanceStorage: 0,
    },
    {
      name: "Standard_F4s_v2",
      cpuUnits: 4,
      memory: 8,
      instanceStorage: 0,
    },
    {
      name: "Standard_F48s_v2",
      cpuUnits: 48,
      memory: 96,
      instanceStorage: 0,
    },
    {
      name: "Standard_F64s_v2",
      cpuUnits: 64,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_F72s_v2",
      cpuUnits: 72,
      memory: 144,
      instanceStorage: 0,
    },
    {
      name: "Standard_F8s",
      cpuUnits: 8,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_F8",
      cpuUnits: 8,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_F8s_v2",
      cpuUnits: 8,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "Standard_G1",
      cpuUnits: 2,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_G2",
      cpuUnits: 4,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_G3",
      cpuUnits: 8,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_G4",
      cpuUnits: 16,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_G5",
      cpuUnits: 32,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS1",
      cpuUnits: 2,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS2",
      cpuUnits: 4,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS3",
      cpuUnits: 8,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS4",
      cpuUnits: 16,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS4-4",
      cpuUnits: 4,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS4-8",
      cpuUnits: 8,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS5",
      cpuUnits: 32,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS5-16",
      cpuUnits: 16,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_GS5-8",
      cpuUnits: 8,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_H16",
      cpuUnits: 16,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_H16m",
      cpuUnits: 16,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_H16mr",
      cpuUnits: 16,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_H16r",
      cpuUnits: 16,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_H8m",
      cpuUnits: 8,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_H8",
      cpuUnits: 8,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_L16s",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_L16s_v2",
      cpuUnits: 16,
      memory: 128,
      instanceStorage: 0,
    },
    {
      name: "Standard_L32s",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_L32s_v2",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_L4s",
      cpuUnits: 4,
      memory: 32,
      instanceStorage: 0,
    },
    {
      name: "Standard_L48s_v2",
      cpuUnits: 48,
      memory: 384,
      instanceStorage: 0,
    },
    {
      name: "Standard_L64s_v2",
      cpuUnits: 64,
      memory: 512,
      instanceStorage: 0,
    },
    {
      name: "Standard_L8s",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_L8s_v2",
      cpuUnits: 8,
      memory: 64,
      instanceStorage: 0,
    },
    {
      name: "Standard_L80s_v2",
      cpuUnits: 80,
      memory: 640,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128",
      cpuUnits: 128,
      memory: 2000,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128-32ms",
      cpuUnits: 32,
      memory: 3800,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128-64ms",
      cpuUnits: 64,
      memory: 3800,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128dms_v2",
      cpuUnits: 128,
      memory: 3892,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128ds_v2",
      cpuUnits: 128,
      memory: 2048,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128m",
      cpuUnits: 128,
      memory: 3800,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128ms",
      cpuUnits: 128,
      memory: 3800,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128ms_v2",
      cpuUnits: 128,
      memory: 3892,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128s",
      cpuUnits: 128,
      memory: 2000,
      instanceStorage: 0,
    },
    {
      name: "Standard_M128s_v2",
      cpuUnits: 128,
      memory: 2048,
      instanceStorage: 0,
    },
    {
      name: "Standard_M192idms_v2",
      cpuUnits: 192,
      memory: 4096,
      instanceStorage: 0,
    },
    {
      name: "Standard_M192ids_v2",
      cpuUnits: 192,
      memory: 2048,
      instanceStorage: 0,
    },
    {
      name: "Standard_M192ims_v2",
      cpuUnits: 192,
      memory: 4096,
      instanceStorage: 0,
    },
    {
      name: "Standard_M192is_v2",
      cpuUnits: 192,
      memory: 2048,
      instanceStorage: 0,
    },
    {
      name: "Standard_M208ms_v2",
      cpuUnits: 208,
      memory: 5700,
      instanceStorage: 0,
    },
    {
      name: "Standard_M208s_v2",
      cpuUnits: 208,
      memory: 2850,
      instanceStorage: 0,
    },
    {
      name: "Standard_M32-16ms",
      cpuUnits: 16,
      memory: 875,
      instanceStorage: 0,
    },
    {
      name: "Standard_M32-8ms",
      cpuUnits: 8,
      memory: 875,
      instanceStorage: 0,
    },
    {
      name: "Standard_M32dms_v2",
      cpuUnits: 32,
      memory: 875,
      instanceStorage: 0,
    },
    {
      name: "Standard_M32ls",
      cpuUnits: 32,
      memory: 256,
      instanceStorage: 0,
    },
    {
      name: "Standard_M32ms",
      cpuUnits: 32,
      memory: 875,
      instanceStorage: 0,
    },
    {
      name: "Standard_M32ms_v2",
      cpuUnits: 32,
      memory: 875,
      instanceStorage: 0,
    },
    {
      name: "Standard_M32ts",
      cpuUnits: 32,
      memory: 192,
      instanceStorage: 0,
    },
    {
      name: "Standard_M416-208ms_v2",
      cpuUnits: 208,
      memory: 11400,
      instanceStorage: 0,
    },
    {
      name: "Standard_M416-208s_v2",
      cpuUnits: 208,
      memory: 5700,
      instanceStorage: 0,
    },
    {
      name: "Standard_M416ms_v2",
      cpuUnits: 416,
      memory: 11400,
      instanceStorage: 0,
    },
    {
      name: "Standard_M416s_v2",
      cpuUnits: 416,
      memory: 5700,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64",
      cpuUnits: 64,
      memory: 1000,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64-16ms",
      cpuUnits: 16,
      memory: 1750,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64-32ms",
      cpuUnits: 32,
      memory: 1750,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64dms_v2",
      cpuUnits: 64,
      memory: 1792,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64ds_v2",
      cpuUnits: 64,
      memory: 1024,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64ls",
      cpuUnits: 64,
      memory: 512,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64m",
      cpuUnits: 64,
      memory: 1750,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64ms",
      cpuUnits: 64,
      memory: 1750,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64ms_v2",
      cpuUnits: 64,
      memory: 1792,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64s",
      cpuUnits: 64,
      memory: 1000,
      instanceStorage: 0,
    },
    {
      name: "Standard_M64s_v2",
      cpuUnits: 64,
      memory: 1024,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC12s_v3",
      cpuUnits: 12,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC16as_T4_v3",
      cpuUnits: 16,
      memory: 110,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC24rs_v3",
      cpuUnits: 24,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC24s_v3",
      cpuUnits: 24,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC4as_T4_v3",
      cpuUnits: 4,
      memory: 28,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC6s_v3",
      cpuUnits: 6,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC64as_T4_v3",
      cpuUnits: 64,
      memory: 440,
      instanceStorage: 0,
    },
    {
      name: "Standard_NC8as_T4_v3",
      cpuUnits: 8,
      memory: 56,
      instanceStorage: 0,
    },
    {
      name: "Standard_NV12s_v2",
      cpuUnits: 12,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_NV12s_v3",
      cpuUnits: 12,
      memory: 112,
      instanceStorage: 0,
    },
    {
      name: "Standard_NV24s_v2",
      cpuUnits: 24,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_NV24s_v3",
      cpuUnits: 24,
      memory: 224,
      instanceStorage: 0,
    },
    {
      name: "Standard_NV48s_v3",
      cpuUnits: 48,
      memory: 448,
      instanceStorage: 0,
    },
    {
      name: "Standard_NV6s_v2",
      cpuUnits: 6,
      memory: 112,
      instanceStorage: 0,
    },
  ],
  [Platform.GCP]: [
    {
      name: "c2-standard-16",
      cpuUnits: 16,
      memory: 66,
      instanceStorage: 9000,
    },
    {
      name: "c2-standard-30",
      cpuUnits: 30,
      memory: 123,
      instanceStorage: 9000,
    },
    {
      name: "c2-standard-4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 9000,
    },
    {
      name: "c2-standard-60",
      cpuUnits: 60,
      memory: 246,
      instanceStorage: 9000,
    },
    {
      name: "c2-standard-8",
      cpuUnits: 8,
      memory: 33,
      instanceStorage: 9000,
    },
    {
      name: "n1-highcpu-16",
      cpuUnits: 16,
      memory: 15,
      instanceStorage: 9000,
    },
    {
      name: "n1-highcpu-2",
      cpuUnits: 2,
      memory: 2,
      instanceStorage: 9000,
    },
    {
      name: "n1-highcpu-32",
      cpuUnits: 32,
      memory: 29,
      instanceStorage: 9000,
    },
    {
      name: "n1-highcpu-4",
      cpuUnits: 4,
      memory: 4,
      instanceStorage: 9000,
    },
    {
      name: "n1-highcpu-64",
      cpuUnits: 64,
      memory: 59,
      instanceStorage: 9000,
    },
    {
      name: "n1-highcpu-8",
      cpuUnits: 8,
      memory: 7,
      instanceStorage: 9000,
    },
    {
      name: "n1-highcpu-96",
      cpuUnits: 96,
      memory: 88,
      instanceStorage: 9000,
    },
    {
      name: "n1-highmem-16",
      cpuUnits: 16,
      memory: 106,
      instanceStorage: 9000,
    },
    {
      name: "n1-highmem-2",
      cpuUnits: 2,
      memory: 13,
      instanceStorage: 9000,
    },
    {
      name: "n1-highmem-32",
      cpuUnits: 32,
      memory: 213,
      instanceStorage: 9000,
    },
    {
      name: "n1-highmem-4",
      cpuUnits: 4,
      memory: 27,
      instanceStorage: 9000,
    },
    {
      name: "n1-highmem-64",
      cpuUnits: 64,
      memory: 426,
      instanceStorage: 9000,
    },
    {
      name: "n1-highmem-8",
      cpuUnits: 8,
      memory: 53,
      instanceStorage: 9000,
    },
    {
      name: "n1-highmem-96",
      cpuUnits: 96,
      memory: 639,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-1",
      cpuUnits: 1,
      memory: 4,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-16",
      cpuUnits: 16,
      memory: 61,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-2",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-32",
      cpuUnits: 32,
      memory: 123,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-4",
      cpuUnits: 4,
      memory: 15,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-64",
      cpuUnits: 64,
      memory: 246,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-8",
      cpuUnits: 8,
      memory: 31,
      instanceStorage: 9000,
    },
    {
      name: "n1-standard-96",
      cpuUnits: 96,
      memory: 369,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-16",
      cpuUnits: 16,
      memory: 16,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-2",
      cpuUnits: 2,
      memory: 2,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-32",
      cpuUnits: 32,
      memory: 33,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-4",
      cpuUnits: 4,
      memory: 4,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-48",
      cpuUnits: 48,
      memory: 49,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-64",
      cpuUnits: 64,
      memory: 66,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-8",
      cpuUnits: 8,
      memory: 8,
      instanceStorage: 9000,
    },
    {
      name: "n2-highcpu-80",
      cpuUnits: 80,
      memory: 82,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-16",
      cpuUnits: 16,
      memory: 131,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-2",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-32",
      cpuUnits: 32,
      memory: 262,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-4",
      cpuUnits: 4,
      memory: 33,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-48",
      cpuUnits: 48,
      memory: 393,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-64",
      cpuUnits: 64,
      memory: 524,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-8",
      cpuUnits: 8,
      memory: 66,
      instanceStorage: 9000,
    },
    {
      name: "n2-highmem-80",
      cpuUnits: 80,
      memory: 655,
      instanceStorage: 9000,
    },
    {
      name: "n2-standard-16",
      cpuUnits: 16,
      memory: 66,
      instanceStorage: 9000,
    },
    {
      name: "n2-standard-2",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 9000,
      default: true,
    },
    {
      name: "n2-standard-32",
      cpuUnits: 32,
      memory: 131,
      instanceStorage: 9000,
    },
    {
      name: "n2-standard-4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 9000,
      controlPlane: true,
    },
    {
      name: "n2-standard-48",
      cpuUnits: 48,
      memory: 197,
      instanceStorage: 9000,
    },
    {
      name: "n2-standard-64",
      cpuUnits: 64,
      memory: 262,
      instanceStorage: 9000,
    },
    {
      name: "n2-standard-8",
      cpuUnits: 8,
      memory: 33,
      instanceStorage: 9000,
    },
    {
      name: "n2-standard-80",
      cpuUnits: 80,
      memory: 328,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-128",
      cpuUnits: 128,
      memory: 131,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-16",
      cpuUnits: 16,
      memory: 16,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-2",
      cpuUnits: 2,
      memory: 2,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-224",
      cpuUnits: 224,
      memory: 229,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-32",
      cpuUnits: 32,
      memory: 33,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-4",
      cpuUnits: 4,
      memory: 4,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-48",
      cpuUnits: 48,
      memory: 49,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-64",
      cpuUnits: 64,
      memory: 66,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-8",
      cpuUnits: 8,
      memory: 8,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-80",
      cpuUnits: 80,
      memory: 82,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highcpu-96",
      cpuUnits: 96,
      memory: 98,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-16",
      cpuUnits: 16,
      memory: 131,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-2",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-32",
      cpuUnits: 32,
      memory: 262,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-4",
      cpuUnits: 4,
      memory: 33,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-48",
      cpuUnits: 48,
      memory: 393,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-64",
      cpuUnits: 64,
      memory: 524,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-8",
      cpuUnits: 8,
      memory: 66,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-80",
      cpuUnits: 80,
      memory: 655,
      instanceStorage: 9000,
    },
    {
      name: "n2d-highmem-96",
      cpuUnits: 96,
      memory: 786,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-128",
      cpuUnits: 128,
      memory: 524,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-16",
      cpuUnits: 16,
      memory: 66,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-2",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-224",
      cpuUnits: 224,
      memory: 918,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-32",
      cpuUnits: 32,
      memory: 131,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-48",
      cpuUnits: 48,
      memory: 197,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-64",
      cpuUnits: 64,
      memory: 262,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-8",
      cpuUnits: 8,
      memory: 33,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-80",
      cpuUnits: 80,
      memory: 328,
      instanceStorage: 9000,
    },
    {
      name: "n2d-standard-96",
      cpuUnits: 96,
      memory: 393,
      instanceStorage: 9000,
    },
    {
      name: "e2-highcpu-16",
      cpuUnits: 16,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "e2-highcpu-2",
      cpuUnits: 2,
      memory: 2,
      instanceStorage: 0,
    },
    {
      name: "e2-highcpu-32",
      cpuUnits: 32,
      memory: 33,
      instanceStorage: 0,
    },
    {
      name: "e2-highcpu-4",
      cpuUnits: 4,
      memory: 4,
      instanceStorage: 0,
    },
    {
      name: "e2-highcpu-8",
      cpuUnits: 8,
      memory: 8,
      instanceStorage: 0,
    },
    {
      name: "e2-highmem-16",
      cpuUnits: 16,
      memory: 131,
      instanceStorage: 0,
    },
    {
      name: "e2-highmem-2",
      cpuUnits: 2,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "e2-highmem-4",
      cpuUnits: 4,
      memory: 33,
      instanceStorage: 0,
    },
    {
      name: "e2-highmem-8",
      cpuUnits: 8,
      memory: 66,
      instanceStorage: 0,
    },
    {
      name: "e2-medium",
      cpuUnits: 2,
      memory: 4,
      instanceStorage: 0,
    },
    {
      name: "e2-micro",
      cpuUnits: 2,
      memory: 1,
      instanceStorage: 0,
    },
    {
      name: "e2-small",
      cpuUnits: 2,
      memory: 2,
      instanceStorage: 0,
    },
    {
      name: "e2-standard-16",
      cpuUnits: 16,
      memory: 66,
      instanceStorage: 0,
    },
    {
      name: "e2-standard-2",
      cpuUnits: 2,
      memory: 8,
      instanceStorage: 0,
    },
    {
      name: "e2-standard-32",
      cpuUnits: 32,
      memory: 131,
      instanceStorage: 0,
    },
    {
      name: "e2-standard-4",
      cpuUnits: 4,
      memory: 16,
      instanceStorage: 0,
    },
    {
      name: "e2-standard-8",
      cpuUnits: 8,
      memory: 33,
      instanceStorage: 0,
    },
    {
      name: "f1-micro",
      cpuUnits: 1,
      memory: 1,
      instanceStorage: 0,
    },
    {
      name: "g1-small",
      cpuUnits: 1,
      memory: 2,
      instanceStorage: 0,
    },
  ],
};

const isDefault = (item: Instance) => item.default === true;

export const defaultInstances: { [platform in Platform]: Instance } = (() => ({
  [Platform.AWS]: platformInstanceMap.AWS.find(isDefault) as Instance,
  [Platform.AZURE]: platformInstanceMap.AZURE.find(isDefault) as Instance,
  [Platform.GCP]: platformInstanceMap.GCP.find(isDefault) as Instance,
  [Platform.VMware]: {
    cpuUnits: 40,
    memory: 128,
    name: "default",
  } as Instance,
  [Platform.RHV]: {
    cpuUnits: 40,
    memory: 128,
    name: "default",
  } as Instance,
  [Platform.BAREMETAL]: {
    cpuUnits: 24,
    memory: 64,
    name: "default",
  } as Instance,
}))();

const isControlPlane = (item: Instance) => item.controlPlane === true;

export const controlPlaneInstances: {
  [platform in Platform]: Instance;
} = (() => ({
  [Platform.AWS]: platformInstanceMap.AWS.find(isControlPlane) as Instance,
  [Platform.AZURE]: platformInstanceMap.AZURE.find(isControlPlane) as Instance,
  [Platform.GCP]: platformInstanceMap.GCP.find(isControlPlane) as Instance,
  [Platform.VMware]: {
    cpuUnits: 6,
    memory: 16,
    name: "controlPlane",
  } as Instance,
  [Platform.RHV]: {
    cpuUnits: 6,
    memory: 16,
    name: "controlPlane",
  } as Instance,
  [Platform.BAREMETAL]: {
    cpuUnits: 6,
    memory: 16,
    name: "controlPlane",
  } as Instance,
}))();
