import { Instance, Platform } from "./types";

type CloudPlatForm = Platform.AWS | Platform.AZURE | Platform.GCP;

type PlatformInstanceMap = {
  [platform in CloudPlatForm]: Instance[];
};

export const platformInstanceMap = {
  [Platform.AWS]: [
    {
      name: "c3.2xlarge",
      memory: 15,
      cpuUnits: 8,
      instanceStorage: 160,
    },
    {
      name: "c3.4xlarge",
      memory: 30,
      cpuUnits: 16,
      instanceStorage: 320,
    },
    {
      name: "c3.8xlarge",
      memory: 60,
      cpuUnits: 32,
      instanceStorage: 640,
    },
    {
      name: "c3.large",
      memory: 3.75,
      cpuUnits: 2,
      instanceStorage: 32,
    },
    {
      name: "c3.xlarge",
      memory: 7.5,
      cpuUnits: 4,
      instanceStorage: 80,
    },
    {
      name: "c5ad.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "c5ad.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "c5ad.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 3800,
    },
    {
      name: "c5ad.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "c5ad.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "c5ad.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "c5ad.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "c5ad.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "c5d.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "c5d.18xlarge",
      memory: 144,
      cpuUnits: 72,
      instanceStorage: 1800,
    },
    {
      name: "c5d.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "c5d.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 200,
    },
    {
      name: "c5d.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 400,
    },
    {
      name: "c5d.9xlarge",
      memory: 72,
      cpuUnits: 36,
      instanceStorage: 900,
    },
    {
      name: "c5d.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 50,
    },
    {
      name: "c5d.metal",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "c5d.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 100,
    },
    {
      name: "c6gd.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "c6gd.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "c6gd.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 474,
    },
    {
      name: "c6gd.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "c6gd.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "c6gd.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "c6gd.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "c6gd.metal",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "c6gd.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "cr1.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 240,
    },
    {
      name: "f1.16xlarge",
      memory: 976,
      cpuUnits: 64,
      instanceStorage: 3760,
    },
    {
      name: "f1.2xlarge",
      memory: 122,
      cpuUnits: 8,
      instanceStorage: 470,
    },
    {
      name: "f1.4xlarge",
      memory: 244,
      cpuUnits: 16,
      instanceStorage: 940,
    },
    {
      name: "g2.2xlarge",
      memory: 15,
      cpuUnits: 8,
      instanceStorage: 60,
    },
    {
      name: "g2.8xlarge",
      memory: 60,
      cpuUnits: 32,
      instanceStorage: 240,
    },
    {
      name: "g4ad.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "g4ad.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "g4ad.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "g4dn.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 900,
    },
    {
      name: "g4dn.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 900,
    },
    {
      name: "g4dn.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 225,
    },
    {
      name: "g4dn.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 225,
    },
    {
      name: "g4dn.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 900,
    },
    {
      name: "g4dn.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 1800,
    },
    {
      name: "g4dn.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 125,
    },
    {
      name: "i2.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 1600,
    },
    {
      name: "i2.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 3200,
    },
    {
      name: "i2.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 6400,
    },
    {
      name: "i2.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 800,
    },
    {
      name: "i3.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 15200,
    },
    {
      name: "i3.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 1900,
    },
    {
      name: "i3.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 3800,
    },
    {
      name: "i3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 7600,
    },
    {
      name: "i3.large",
      memory: 15.25,
      cpuUnits: 2,
      instanceStorage: 475,
    },
    {
      name: "i3.metal",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 15200,
    },
    {
      name: "i3.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 950,
    },
    {
      name: "i3en.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 30000,
    },
    {
      name: "i3en.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 60000,
    },
    {
      name: "i3en.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 5000,
    },
    {
      name: "i3en.3xlarge",
      memory: 96,
      cpuUnits: 12,
      instanceStorage: 7500,
    },
    {
      name: "i3en.6xlarge",
      memory: 192,
      cpuUnits: 24,
      instanceStorage: 15000,
    },
    {
      name: "i3en.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 1250,
    },
    {
      name: "i3en.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 60000,
    },
    {
      name: "i3en.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 2500,
    },
    {
      name: "m3.2xlarge",
      memory: 30,
      cpuUnits: 8,
      instanceStorage: 160,
    },
    {
      name: "m3.large",
      memory: 7.5,
      cpuUnits: 2,
      instanceStorage: 32,
    },
    {
      name: "m3.medium",
      memory: 3.75,
      cpuUnits: 1,
      instanceStorage: 4,
    },
    {
      name: "m3.xlarge",
      memory: 15,
      cpuUnits: 4,
      instanceStorage: 80,
    },
    {
      name: "m5ad.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "m5ad.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "m5ad.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5ad.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "m5ad.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "m5ad.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "m5ad.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "m5ad.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "m5d.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "m5d.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "m5d.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5d.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "m5d.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "m5d.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "m5d.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "m5d.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5d.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "m5dn.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "m5dn.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "m5dn.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5dn.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "m5dn.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "m5dn.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "m5dn.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "m5dn.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "m5dn.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "m6gd.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "m6gd.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "m6gd.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 474,
    },
    {
      name: "m6gd.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "m6gd.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "m6gd.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "m6gd.medium",
      memory: 4,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "m6gd.metal",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "m6gd.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "p3dn.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 1800,
    },
    {
      name: "p4d.24xlarge",
      memory: 1152,
      cpuUnits: 96,
      instanceStorage: 8000,
    },
    {
      name: "r3.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 160,
    },
    {
      name: "r3.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 320,
    },
    {
      name: "r3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 640,
    },
    {
      name: "r3.large",
      memory: 15.25,
      cpuUnits: 2,
      instanceStorage: 32,
    },
    {
      name: "r3.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 80,
    },
    {
      name: "r5ad.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "r5ad.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "r5ad.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5ad.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "r5ad.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "r5ad.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "r5ad.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "r5ad.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "r5d.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "r5d.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "r5d.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5d.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "r5d.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "r5d.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "r5d.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "r5d.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5d.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "r5dn.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "r5dn.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 2400,
    },
    {
      name: "r5dn.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5dn.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "r5dn.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 600,
    },
    {
      name: "r5dn.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1200,
    },
    {
      name: "r5dn.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "r5dn.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 3600,
    },
    {
      name: "r5dn.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "r6gd.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "r6gd.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "r6gd.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 474,
    },
    {
      name: "r6gd.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "r6gd.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "r6gd.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "r6gd.medium",
      memory: 8,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "r6gd.metal",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "r6gd.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "x1.16xlarge",
      memory: 976,
      cpuUnits: 64,
      instanceStorage: 1920,
    },
    {
      name: "x1.32xlarge",
      memory: 1952,
      cpuUnits: 128,
      instanceStorage: 3840,
    },
    {
      name: "x1e.16xlarge",
      memory: 1952,
      cpuUnits: 64,
      instanceStorage: 1920,
    },
    {
      name: "x1e.2xlarge",
      memory: 244,
      cpuUnits: 8,
      instanceStorage: 240,
    },
    {
      name: "x1e.32xlarge",
      memory: 3904,
      cpuUnits: 128,
      instanceStorage: 3840,
    },
    {
      name: "x1e.4xlarge",
      memory: 488,
      cpuUnits: 16,
      instanceStorage: 480,
    },
    {
      name: "x1e.8xlarge",
      memory: 976,
      cpuUnits: 32,
      instanceStorage: 960,
    },
    {
      name: "x1e.xlarge",
      memory: 122,
      cpuUnits: 4,
      instanceStorage: 120,
    },
    {
      name: "x2gd.12xlarge",
      memory: 768,
      cpuUnits: 48,
      instanceStorage: 2850,
    },
    {
      name: "x2gd.16xlarge",
      memory: 1024,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "x2gd.2xlarge",
      memory: 128,
      cpuUnits: 8,
      instanceStorage: 475,
    },
    {
      name: "x2gd.4xlarge",
      memory: 256,
      cpuUnits: 16,
      instanceStorage: 950,
    },
    {
      name: "x2gd.8xlarge",
      memory: 512,
      cpuUnits: 32,
      instanceStorage: 1900,
    },
    {
      name: "x2gd.large",
      memory: 32,
      cpuUnits: 2,
      instanceStorage: 118,
    },
    {
      name: "x2gd.medium",
      memory: 16,
      cpuUnits: 1,
      instanceStorage: 59,
    },
    {
      name: "x2gd.metal",
      memory: 1024,
      cpuUnits: 64,
      instanceStorage: 3800,
    },
    {
      name: "x2gd.xlarge",
      memory: 64,
      cpuUnits: 4,
      instanceStorage: 237,
    },
    {
      name: "z1d.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "z1d.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 300,
    },
    {
      name: "z1d.3xlarge",
      memory: 96,
      cpuUnits: 12,
      instanceStorage: 450,
    },
    {
      name: "z1d.6xlarge",
      memory: 192,
      cpuUnits: 24,
      instanceStorage: 900,
    },
    {
      name: "z1d.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 75,
    },
    {
      name: "z1d.metal",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 1800,
    },
    {
      name: "z1d.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 150,
    },
    {
      name: "a1.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "a1.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "a1.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "a1.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "a1.metal",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "a1.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c1.medium",
      memory: 1.7,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c1.xlarge",
      memory: 7,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c4.2xlarge",
      memory: 15,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c4.4xlarge",
      memory: 30,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c4.8xlarge",
      memory: 60,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "c4.large",
      memory: 3.75,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c4.xlarge",
      memory: 7.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c5.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c5.18xlarge",
      memory: 144,
      cpuUnits: 72,
      instanceStorage: 0,
    },
    {
      name: "c5.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "c5.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c5.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c5.9xlarge",
      memory: 72,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "c5.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c5.metal",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "c5.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c5a.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c5a.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c5a.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "c5a.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c5a.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c5a.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "c5a.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c5a.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c5n.18xlarge",
      memory: 192,
      cpuUnits: 72,
      instanceStorage: 0,
    },
    {
      name: "c5n.2xlarge",
      memory: 21,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c5n.4xlarge",
      memory: 42,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c5n.9xlarge",
      memory: 96,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "c5n.large",
      memory: 5.25,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c5n.metal",
      memory: 192,
      cpuUnits: 72,
      instanceStorage: 0,
    },
    {
      name: "c5n.xlarge",
      memory: 10.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c6g.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c6g.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6g.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c6g.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c6g.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "c6g.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c6g.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "c6g.metal",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6g.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "c6gn.12xlarge",
      memory: 96,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "c6gn.16xlarge",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6gn.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "c6gn.4xlarge",
      memory: 32,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "c6gn.8xlarge",
      memory: 64,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "c6gn.large",
      memory: 4,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "c6gn.medium",
      memory: 2,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "c6gn.metal",
      memory: 128,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "c6gn.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "cc2.8xlarge",
      memory: 60.5,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "d2.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "d2.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "d2.8xlarge",
      memory: 244,
      cpuUnits: 36,
      instanceStorage: 0,
    },
    {
      name: "d2.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "d3.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "d3.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "d3.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "d3.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "d3en.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "d3en.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "d3en.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "d3en.6xlarge",
      memory: 96,
      cpuUnits: 24,
      instanceStorage: 0,
    },
    {
      name: "d3en.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "d3en.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "g3.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "g3.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "g3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "g3s.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "h1.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "h1.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "h1.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "h1.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "hs1.8xlarge",
      memory: 117,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "i2.large",
      memory: 15,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "inf1.24xlarge",
      memory: 192,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "inf1.2xlarge",
      memory: 16,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "inf1.6xlarge",
      memory: 48,
      cpuUnits: 24,
      instanceStorage: 0,
    },
    {
      name: "inf1.xlarge",
      memory: 8,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m1.large",
      memory: 7.5,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m1.medium",
      memory: 3.75,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "m1.small",
      memory: 1.7,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "m1.xlarge",
      memory: 15,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m2.2xlarge",
      memory: 34.2,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m2.4xlarge",
      memory: 68.4,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m2.xlarge",
      memory: 17.1,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m4.10xlarge",
      memory: 160,
      cpuUnits: 40,
      instanceStorage: 0,
    },
    {
      name: "m4.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m4.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m4.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m4.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m4.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m5.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m5.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
      default: true,
    },
    {
      name: "m5.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m5.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m5.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m5a.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5a.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m5a.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5a.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5a.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m5a.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m5a.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m5a.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m5n.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5n.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m5n.24xlarge",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5n.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5n.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m5n.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m5n.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m5n.metal",
      memory: 384,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "m5n.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m5zn.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5zn.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m5zn.3xlarge",
      memory: 48,
      cpuUnits: 12,
      instanceStorage: 0,
    },
    {
      name: "m5zn.6xlarge",
      memory: 96,
      cpuUnits: 24,
      instanceStorage: 0,
    },
    {
      name: "m5zn.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m5zn.metal",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m5zn.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "m6g.12xlarge",
      memory: 192,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "m6g.16xlarge",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m6g.2xlarge",
      memory: 32,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "m6g.4xlarge",
      memory: 64,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "m6g.8xlarge",
      memory: 128,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "m6g.large",
      memory: 8,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "m6g.medium",
      memory: 4,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "m6g.metal",
      memory: 256,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "m6g.xlarge",
      memory: 16,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "mac1.metal",
      memory: 32,
      cpuUnits: 12,
      instanceStorage: 0,
    },
    {
      name: "p2.16xlarge",
      memory: 732,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "p2.8xlarge",
      memory: 488,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "p2.xlarge",
      memory: 61,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "p3.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "p3.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "p3.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r4.16xlarge",
      memory: 488,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r4.2xlarge",
      memory: 61,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r4.4xlarge",
      memory: 122,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r4.8xlarge",
      memory: 244,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r4.large",
      memory: 15.25,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r4.xlarge",
      memory: 30.5,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5a.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5a.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5a.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5a.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5a.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5a.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5a.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5a.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5b.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5b.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5b.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5b.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5b.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5b.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5b.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5b.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5b.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r5n.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r5n.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r5n.24xlarge",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5n.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r5n.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r5n.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r5n.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r5n.metal",
      memory: 768,
      cpuUnits: 96,
      instanceStorage: 0,
    },
    {
      name: "r5n.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "r6g.12xlarge",
      memory: 384,
      cpuUnits: 48,
      instanceStorage: 0,
    },
    {
      name: "r6g.16xlarge",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r6g.2xlarge",
      memory: 64,
      cpuUnits: 8,
      instanceStorage: 0,
    },
    {
      name: "r6g.4xlarge",
      memory: 128,
      cpuUnits: 16,
      instanceStorage: 0,
    },
    {
      name: "r6g.8xlarge",
      memory: 256,
      cpuUnits: 32,
      instanceStorage: 0,
    },
    {
      name: "r6g.large",
      memory: 16,
      cpuUnits: 2,
      instanceStorage: 0,
    },
    {
      name: "r6g.medium",
      memory: 8,
      cpuUnits: 1,
      instanceStorage: 0,
    },
    {
      name: "r6g.metal",
      memory: 512,
      cpuUnits: 64,
      instanceStorage: 0,
    },
    {
      name: "r6g.xlarge",
      memory: 32,
      cpuUnits: 4,
      instanceStorage: 0,
    },
    {
      name: "u-12tb1.metal",
      memory: 12288,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-18tb1.metal",
      memory: 18432,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-24tb1.metal",
      memory: 24576,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-6tb1.metal",
      memory: 6144,
      cpuUnits: 448,
      instanceStorage: 0,
    },
    {
      name: "u-9tb1.metal",
      memory: 9216,
      cpuUnits: 448,
      instanceStorage: 0,
    },
  ],
};
